apiVersion: batch/v1
kind: CronJob
metadata:
  name: node-labeler
  namespace: kube-system
spec:
  schedule: "*/1 * * * *"  # Every minute
  jobTemplate:
    spec:
      template:
        spec:
          serviceAccountName: node-labeler
          containers:
          - name: labeler
            image: bitnami/kubectl:latest
            command:
            - /bin/sh
            - -c
            - |
              # Label worker nodes without role
              kubectl get nodes -l '!node-role.kubernetes.io/control-plane,!node-role.kubernetes.io/worker' -o name | fgrep "k8s-" | \
              xargs -I {} kubectl label {} node-role.kubernetes.io/worker=
          restartPolicy: OnFailure
---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: node-labeler
  namespace: kube-system
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: node-labeler
rules:
- apiGroups: [""]
  resources: ["nodes"]
  verbs: ["get", "list", "patch"]
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: node-labeler
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: node-labeler
subjects:
- kind: ServiceAccount
  name: node-labeler
  namespace: kube-system